import 'nlu_models.dart';

/// Niyet başına DOĞAL Türkçe örnek cümleler — eşleştirici (nlu_phrase_matcher)
/// bunları "kalıp sözlüğü" olarak kullanır: öğrencinin cümlesi hangi
/// örneklere ne kadar benziyorsa o niyete o kadar puan verilir. Sözlük bir
/// `if (contains)` zinciri DEĞİL, veridir.
///
/// Yazım kuralları:
///  * Örnekler diyakritikli ya da diyakritiksiz yazılabilir; eşleştirmeden
///    önce ikisi de katlanır (bkz. TrText.fold).
///  * Ders adları ve katalogdaki konu adları eşleştirmede `_ders_` / `_konu_`
///    yer tutucusuna çevrilir; süre ifadeleri `_sure_` olur. Bu yüzden
///    "matematikte zorlanıyorum" örneği "fizikte zorlanıyorum"u da kapsar.
///  * Bir örnek YALNIZ bir niyete aittir (tekrar yok); ortak ifadeler için
///    kural katmanı (nlu_rules) kullanılır.
class NluPhrases {
  const NluPhrases._();

  static const Map<CoachIntent, List<String>> byIntent = {
    // ------------------------------------------------------------------
    CoachIntent.needPlan: [
      'bana bir plan yap',
      'bana plan yapar mısın',
      'çalışma planı hazırla',
      'bugün için bir plan çıkar',
      'bu hafta için program yap',
      'haftalık program hazırla bana',
      'günümü planlar mısın',
      'planımı sen kur',
      'ders programı oluştur',
      'bir çalışma programı lazım',
      'bana program lazım',
      'plan yapmama yardım et',
      'planlama yapamıyorum sen yap',
      'düzenli bir plan istiyorum',
      'günlük plan çıkarır mısın',
      'haftamı planlar mısın',
      'bana bir çalışma takvimi hazırla',
      'sen benim için plan yap',
      'planı senden bekliyorum',
      'yeni bir plan oluşturalım',
      'planımı baştan yap',
      'çalışma planım yok bir tane yap',
      'bana uygun bir program çıkar',
      'plan kur bana',
      'ben plan yapamıyorum sen yapsana',
      'bugünü planla',
      'yarın için plan hazırla',
      'sınava kadar bir plan yap',
      'bir haftalık program yapar mısın',
      'günlük çalışma programı hazırlar mısın',
      'ders çalışma planı lazım',
      'bana planlı bir düzen kur',
      'otomatik plan oluştur',
      'planla beni',
      'kendi planımı yapamadım sen hallet',
    ],
    // ------------------------------------------------------------------
    CoachIntent.needRecommendation: [
      'bana bir öneri ver',
      'ne önerirsin',
      'ne tavsiye edersin',
      'bana bir şey öner',
      'sence ne yapmalıyım',
      'bana tavsiye verir misin',
      'öneri istiyorum',
      'bir öneride bulunur musun',
      'ne çalışmamı önerirsin',
      'hangi konuya çalışmamı önerirsin',
      'hangi derse çalışmalıyım',
      'hangi derse bakayım',
      'sen ne dersin ne çalışayım',
      'bugün ne çalışsam',
      'bugün ne çalışayım',
      'ne çalışmalıyım',
      'neye çalışayım',
      'neye çalışsam iyi olur',
      'ne çalışsam bilmiyorum',
      'çalışacak bir şey öner',
      'bana çalışacak konu söyle',
      'bana konu öner',
      'hangi konuyu çalışayım',
      'bugün hangi konuya bakmalıyım',
      'bugün için önerin var mı',
      'bana bugün için bir şey söyle',
      'bir konu seç bana',
      'bana bir ders seç',
      'en mantıklı çalışma ne olur',
      'şimdi hangi ders daha mantıklı',
      'önerin nedir',
      'ne yapsam iyi olur çalışma olarak',
      'çalışmak için bir fikir ver',
      'bugün neyi öncelemeliyim',
      'önceliğim ne olmalı',
    ],
    // ------------------------------------------------------------------
    CoachIntent.needStartPoint: [
      'nereden başlayayım',
      'nerden başlasam',
      'nereden başlamalıyım',
      'nereden başlamam lazım',
      'neresinden başlayayım',
      'nereden başlasam bilmiyorum',
      'ne ile başlayayım',
      'neyle başlamalıyım',
      'hangi konuyla başlayayım',
      'hangi dersle başlayayım',
      'nasıl başlayacağım',
      'nasıl başlayayım',
      'başlangıç noktası ne olmalı',
      'başlamak için ne yapmalıyım',
      'ilk ne yapmalıyım',
      'ilk hangi konuya bakayım',
      'sıfırdan nasıl başlarım',
      'nereye başlayacağımı bilmiyorum',
      'nerden başlayacağımı şaşırdım',
      'başlayamıyorum nerden başlayayım',
      'ilk adım ne olmalı',
      'ilk adımı söyle',
      'nereden girsem',
      'nereden tutsam',
      'derse nereden başlayayım',
      'matematiğe nereden başlayayım',
      'geride kaldım nereden başlayayım',
      'hiçbir şey bilmiyorum nereden başlayayım',
      'baştan başlamak istiyorum nereden başlarım',
      'başlangıç için tavsiyen ne',
      'çalışmaya nereden başlayayım',
      'ilk önce hangi konuyu çalışmalıyım',
      'öncelikle neye bakayım',
      'nasıl bir yolla başlayayım',
      'nereden çalışmaya başlasam',
    ],
    // ------------------------------------------------------------------
    CoachIntent.whatToDoNow: [
      'şimdi ne yapayım',
      'şimdi ne yapmalıyım',
      'şu an ne yapmalıyım',
      'şu an ne çalışayım',
      'şimdi ne çalışsam',
      'hemen ne yapayım',
      'şimdi neye çalışayım',
      'şu anda ne yapabilirim',
      'ne yapayım şimdi',
      'şimdi hangi işe bakayım',
      'sıradaki iş ne',
      'sırada ne var',
      'şimdi sırada ne var',
      'bir sonraki adım ne',
      'şimdi ne çalışmam gerekiyor',
      'şu an yapmam gereken ne',
      'şimdi yapılacak ne var',
      'ne yapacağımı bilmiyorum şimdi',
      'ne yapacağımı şaşırdım',
      'ne yapacağım',
      'ne yapmam lazım',
      'ne yapmalıyım',
      'napayım şimdi',
      'naapıyım şimdi',
      'ne yapıyoruz şimdi',
      'şimdi ne var programda',
      'bugün yapmam gereken ne',
      'bugün ne var',
      'bugünkü işim ne',
      'bugünün odağı ne',
      'ilk yapacağım iş ne',
      'hangisini yapayım şimdi',
      'şimdi neye odaklanayım',
      'şu an neye odaklanmalıyım',
      'hadi bir şey söyle yapayım',
    ],
    // ------------------------------------------------------------------
    CoachIntent.studySessionRequest: [
      'çalışma başlat',
      'çalışmaya başlayalım',
      'hadi çalışalım',
      'bir oturum başlat',
      'odak seansı başlat',
      'odak modu aç',
      'sayaç başlat',
      'kronometre başlat',
      'pomodoro başlat',
      'çalışma seansı aç',
      'bir çalışma bloğu başlat',
      'hemen başlayalım',
      'başlat şunu',
      'çalışmaya başlamak istiyorum',
      'seansı başlatalım',
      'zamanlayıcı kur',
      'şimdi çalışmaya başlıyorum',
      'başlıyorum',
      'kolları sıvadım başlayalım',
      'çalışma moduna geçelim',
      'bir blok çalışalım',
      'birlikte çalışalım',
      'çalışma zamanı başlasın',
      'odaklanmak istiyorum başlat',
      'odaklanma seansı aç',
      'hadi başlayalım bakalım',
      'ders çalışmaya oturdum başlat',
      'masaya oturdum başlayalım',
      'çalışmayı başlat',
      'sürem başlasın',
    ],
    // ------------------------------------------------------------------
    CoachIntent.subjectGuidance: [
      'matematiğe nasıl çalışmalıyım',
      'matematik için ne yapmalıyım',
      'matematiği nasıl çalışayım',
      'matematik çalışacağım ne yapayım',
      'matematik için strateji ver',
      'matematik nasıl çalışılır',
      'matematikte ne çalışayım',
      'matematikten ne çalışsam',
      'matematiğe nereden bakayım',
      'matematiğe yardım et',
      'matematik için bir öneri',
      'matematikte hangi konuya çalışayım',
      'fiziğe nasıl çalışayım',
      'fizik için tavsiye ver',
      'fizikte ne çalışmalıyım',
      'kimyayı nasıl çalışmalıyım',
      'kimya için ne önerirsin',
      'biyolojiye nasıl çalışayım',
      'biyolojide ne yapmalıyım',
      'türkçeye nasıl çalışmalıyım',
      'türkçede ne çalışayım',
      'tarihe nasıl çalışmak lazım',
      'tarih için öneri ver',
      'coğrafyayı nasıl çalışayım',
      'coğrafyada ne çalışayım',
      'geometriye nasıl çalışmalıyım',
      'geometri için ne yapayım',
      'edebiyata nasıl çalışayım',
      'edebiyat için ne önerirsin',
      'felsefe için tavsiye',
      'ingilizceye nasıl çalışayım',
      'ingilizcede ne yapmalıyım',
      'bugün matematik çalışsam mı',
      'bu derse nasıl çalışayım',
    ],
    // ------------------------------------------------------------------
    CoachIntent.topicGuidance: [
      'türevi nasıl çalışmalıyım',
      'türev için ne yapmalıyım',
      'türeve nereden bakayım',
      'türeve ne kadar süre ayırayım',
      'paragrafa nasıl çalışayım',
      'paragraf için ne yapmalıyım',
      'paragrafa nasıl başlayayım',
      'limiti nasıl çalışayım',
      'integrali nasıl çalışmalıyım',
      'fonksiyonlara nasıl çalışayım',
      'olasılığı nasıl çalışayım',
      'trigonometriye nasıl bakayım',
      'logaritma için ne yapayım',
      'bu konuyu nasıl çalışayım',
      'bu konuya nasıl çalışmalıyım',
      'bu konuyu ne zaman çalışayım',
      'bu konuya ne kadar zaman ayırayım',
      'bu konu için ne önerirsin',
      'bu konuya nereden başlayayım',
      'şu konuyu nasıl çalışırım',
      'bu konuyu planıma ekle',
      'konuyu çalışacağım ne yapayım',
      'konu çalışma yöntemi öner',
      'konuya nasıl yaklaşayım',
      'bu konuya yardım',
      'elektrik akımına nasıl çalışayım',
      'organik kimyaya nasıl çalışmalıyım',
      'hücreye nasıl çalışayım',
      'osmanlı tarihine nasıl çalışayım',
      'dil bilgisine nasıl çalışmalıyım',
    ],
    // ------------------------------------------------------------------
    CoachIntent.timeConstraint: [
      'bugün sadece 30 dakikam var',
      'sadece bir saatim var',
      'yarım saatim var',
      'bugün çok az vaktim var',
      'vaktim çok kısıtlı',
      'zamanım çok az',
      'sadece 20 dakikam var ne çalışayım',
      'elimde 45 dakika var',
      'bir saatim var ne yapayım',
      'iki saatim var ne çalışmalıyım',
      'bugün sadece 1 saat çalışabilirim',
      'en fazla 40 dakika çalışabilirim',
      'kısa bir zamanım var',
      'vaktim yok ama biraz çalışmak istiyorum',
      'çok vaktim yok',
      'az zamanda ne yapabilirim',
      'kısa sürede ne çalışabilirim',
      'yarım saat için bir şey öner',
      '15 dakikam var',
      'sadece 10 dakika ayırabilirim',
      'birazdan çıkacağım 30 dakikam var',
      'bugün toplam 2 saatim var',
      'bugün 3 saat çalışabilirim',
      'günde sadece 1 saat çalışabiliyorum',
      'zamanım kısıtlı plan yap',
      'süre az ne yapabilirim',
      'elimde bir saat var ne yapayım',
      'bugün vaktim daralmış',
      'yarım saatlik bir şey var mı',
      'çok az vaktim kaldı bugün',
      'sadece kırk beş dakikam var',
      'kısa bir oturum yapalım',
      'hızlı bir çalışma önerir misin',
      'iş çıktı sadece bir saatim var',
      'bugün vakit bulamıyorum çok az var',
    ],
    // ------------------------------------------------------------------
    CoachIntent.strugglingSubject: [
      'matematikte zorlanıyorum',
      'matematiği anlamıyorum',
      'matematik çok zor geliyor',
      'matematikte çok zayıfım',
      'matematiğim çok kötü',
      'matematikte hiçbir şey bilmiyorum',
      'matematik bana çok zor',
      'matematiği bir türlü öğrenemiyorum',
      'matematik hiç oturmuyor',
      'matematikte yapamıyorum',
      'matematikte çok eksiğim var',
      'matematikte eksiklerim çok',
      'fizikte zorlanıyorum',
      'fiziği anlamıyorum',
      'fizik çok zor',
      'kimyada çok zorlanıyorum',
      'kimya hiç anlamıyorum',
      'biyolojide zayıfım',
      'biyolojiyi ezberleyemiyorum',
      'türkçede zorlanıyorum',
      'türkçe zayıf kaldı',
      'tarihi ezberleyemiyorum',
      'tarihte çok eksiğim var',
      'coğrafyada zorlanıyorum',
      'geometri hiç gelmiyor',
      'geometride çok zayıfım',
      'edebiyatta zorlanıyorum',
      'ingilizcede çok zayıfım',
      'ingilizce kelime ezberleyemiyorum',
      'felsefede zorlanıyorum',
      'bu derste çok zorlanıyorum',
      'bu dersi anlamıyorum',
      'bu ders bana zor geliyor',
      'derslerde çok eksiğim var',
      'hiçbir derste iyi değilim',
      'bir türlü oturtamıyorum matematiği',
      'matematik beynime girmiyor',
      'çalışıyorum ama matematik gelmiyor',
      'matematikte hep tıkanıyorum',
      'matematikte çok geriyim bilgi olarak',
    ],
    // ------------------------------------------------------------------
    CoachIntent.strugglingTopic: [
      'türevde zorlanıyorum',
      'türevi anlamıyorum',
      'türev hiç oturmadı',
      'türev çok zor geliyor',
      'limitte zorlanıyorum',
      'integrali anlamıyorum',
      'integral çok zor',
      'fonksiyonlarda zorlanıyorum',
      'fonksiyonları hiç anlamıyorum',
      'olasılıkta zorlanıyorum',
      'permütasyon kombinasyonu anlamıyorum',
      'trigonometride zorlanıyorum',
      'logaritmayı bir türlü anlayamadım',
      'polinomları anlayamıyorum',
      'problemlerde zorlanıyorum',
      'paragrafta zorlanıyorum',
      'paragrafı anlamıyorum',
      'paragraf çözemiyorum',
      'dil bilgisinde zorlanıyorum',
      'elektrikte zorlanıyorum',
      'manyetizmayı anlamıyorum',
      'mol kavramını anlamıyorum',
      'organik kimyada zorlanıyorum',
      'genetikte zorlanıyorum',
      'hücre bölünmesini anlamıyorum',
      'bu konuda zorlanıyorum',
      'bu konuyu anlamıyorum',
      'bu konu hiç oturmuyor',
      'bu konuyu bir türlü kavrayamadım',
      'bu konu çok zor geliyor',
      'bu konuda sürekli tıkanıyorum',
      'şu konuyu anlayamıyorum',
      'bu konuyu ne kadar çalışsam da olmuyor',
      'konuyu anlamıyorum ne yapayım',
      'bu konuda hep takılıyorum',
    ],
    // ------------------------------------------------------------------
    CoachIntent.questionPerformanceProblem: [
      'sürekli yanlış yapıyorum',
      'soruları hep yanlış yapıyorum',
      'paragrafta sürekli yanlış yapıyorum',
      'matematik sorularını çözemiyorum',
      'soru çözerken takılıyorum',
      'soruları bitiremiyorum',
      'sorularda süre yetmiyor',
      'soru çözme hızım çok düşük',
      'çok yavaş soru çözüyorum',
      'testlerde hep aynı hatayı yapıyorum',
      'dikkatsizlikten yanlış yapıyorum',
      'bildiğim soruları yanlış yapıyorum',
      'sorularda hep saçmalıyorum',
      'soru çözünce yanlışlarım çok çıkıyor',
      'test çözerken yanlışım çok oluyor',
      'yanlış sayım çok fazla',
      'yanlışlarım hiç azalmıyor',
      'aynı tür soruda hep yanılıyorum',
      'soruyu okuyunca ne istediğini anlamıyorum',
      'soruyu yanlış anlıyorum',
      'sorularda zaman kaybediyorum',
      'soru çözmede çok yavaşım',
      'yanlış yaptığım soruları toparlayamıyorum',
      'boş bırakıyorum soruları',
      'soruyu çözemeyince panikliyorum',
      'sorular çok zor geliyor',
      'test çözüyorum ama net yapamıyorum',
      'soruda takılıp kalıyorum',
      'paragraf sorularını yanlış yapıyorum',
      'problem sorularında hep yanlış çıkıyor',
      'fizik sorularını çözemiyorum',
      'geometri sorularında takılıyorum',
      'dikkat hatası yapıyorum hep',
      'işlem hatası çok yapıyorum',
      'yanlış yapıyorum hep',
    ],
    // ------------------------------------------------------------------
    CoachIntent.mockExamProblem: [
      'denemelerim kötü geçiyor',
      'denemede netlerim düşük',
      'deneme netlerim artmıyor',
      'denemelerde bir türlü net yapamıyorum',
      'denemeyi bitiremiyorum',
      'denemede süre yetmiyor',
      'deneme sonuçlarım berbat',
      'son denemem çok kötüydü',
      'denemelerde sürekli aynı yerde yanlış yapıyorum',
      'deneme netlerim düştü',
      'denemede matematik netim çok düşük',
      'denemede matematik hiç yapamadım',
      'denemelerde matematik netim yok gibi',
      'denemeden sonra moralim bozuldu',
      'deneme sonucum beni çok üzdü',
      'deneme analizi nasıl yapmalıyım',
      'denemeleri nasıl değerlendireyim',
      'denemede yanlışlarımı nasıl çalışayım',
      'denemelerde paragrafı bitiremiyorum',
      'denemede fiziği boş bıraktım',
      'denemede stres yapıyorum',
      'deneme sınavında donup kalıyorum',
      'deneme çözerken heyecanlanıyorum',
      'denemelerde net atlayamıyorum',
      'netlerim yerinde sayıyor',
      'netlerim bir türlü yükselmiyor',
      'net artışı göremiyorum denemelerde',
      'tyt denemelerim kötü',
      'ayt denemelerim çok düşük',
      'denemelerde hedefimin çok altındayım',
      'denemede hedef netime ulaşamıyorum',
      'deneme sonuçlarım hep aynı',
      'denemede yapamadım',
      'deneme çok kötü geçti',
      'deneme sonucum rezil',
    ],
    // ------------------------------------------------------------------
    CoachIntent.examUrgency: [
      'yarın deneme var',
      'yarın sınav var',
      'yarın denemem var çok eksiğim var',
      'yarın matematik sınavım var',
      'yarın yazılı var ne çalışayım',
      'bugün deneme var',
      'bu akşam denemem var',
      'yarın deneme var matematikte hiçbir şey bilmiyorum',
      'sınava çok az kaldı',
      'sınava az kaldı yetişemeyeceğim',
      'sınav yaklaşıyor ne yapmalıyım',
      'sınava kadar ne yapmalıyım',
      'sınava kaç gün kaldı ne çalışayım',
      'sınava haftalar kaldı acil ne yapayım',
      'deneme sınavı yaklaşıyor hazırlanmalıyım',
      'haftaya deneme var',
      'haftaya sınavım var',
      'hafta sonu deneme var hazırlıksızım',
      'birkaç gün sonra sınav var',
      'üç gün sonra yazılı var',
      'iki gün sonra sınavım var',
      'sınav çok yakın',
      'sınavım yarın ne yapmalıyım',
      'deneme öncesi ne çalışayım',
      'sınav öncesi son tekrar için ne çalışayım',
      'denemeye hazırlanmam lazım',
      'yarın sınav çok eksiğim var',
      'yks yaklaşıyor hazır değilim',
      'yks ye çok az kaldı',
      'tyt ye az kaldı ne yapayım',
      'sınava hazır değilim vakit yok',
      'sınava yetişemem gibi',
      'zaman yok sınav çok yakın',
      'yarınki sınav için acil çalışmam lazım',
      'acil sınav çalışması lazım',
      'sınava kısa sürede nasıl hazırlanırım',
    ],
    // ------------------------------------------------------------------
    CoachIntent.behindSchedule: [
      'matematikte çok geride kaldım',
      'çok geride kaldım',
      'programın çok gerisindeyim',
      'planımın gerisindeyim',
      'planı yetiştiremiyorum',
      'yetişemiyorum',
      'yetişmiyor',
      'yetişemedim',
      'yetiştiremiyorum bir türlü',
      'çok geriye düştüm',
      'geri kaldım hepsinden',
      'diğerlerinden çok geriyim',
      'müfredatın çok gerisindeyim',
      'konular birikti',
      'görevlerim birikti',
      'çalışmalarım aksadı',
      'planım tamamen aksadı',
      'programım bozuldu',
      'programım çöktü',
      'plan sapması yaşadım',
      'yapmam gereken çok şey birikti',
      'bir haftadır hiçbir şey yapamadım geride kaldım',
      'günlerdir çalışmıyorum geri kaldım',
      'konuları bitiremedim',
      'konu bitiremiyorum hep geride kalıyorum',
      'takvimin gerisine düştüm',
      'geç kaldım',
      'çok geç kaldım artık',
      'hepsi yarım kaldı',
      'yarım bıraktığım konular çok',
      'ilerleme hızım yetmiyor',
      'bu hızla yetişemem',
      'matematikte geriyim yetişmem lazım',
      'geriye düştüm ne yapayım',
      'gecikmiş görevlerim var',
      'ertelediğim görevler çok birikti',
      'her şeyi erteledim şimdi geriyim',
      'çok ertelemişim',
      'geri kalmışım',
      'gerilerde kaldım',
    ],
    // ------------------------------------------------------------------
    CoachIntent.tooMuchWork: [
      'çok fazla işim var',
      'çok fazla konu var',
      'çok görevim var',
      'yapacak çok şey var',
      'her şey üst üste geldi',
      'hepsini yapamam',
      'hepsini yetiştiremem',
      'bu kadar konuyu bitiremem',
      'çok yoğunum',
      'çok yoğun bir programım var',
      'programım çok dolu',
      'yükümüz çok fazla',
      'bunaldım çok iş var',
      'boğuldum görevlerin altında',
      'görevler yığıldı',
      'iş yükü çok ağır',
      'çok konu var nereye yetişeceğim',
      'ders yükü çok fazla',
      'bu kadar şeyi nasıl yapacağım',
      'her şeyi birden yapamıyorum',
      'liste çok uzun',
      'görev listem çok uzun',
      'çok fazla ödevim var',
      'yapılacaklar çok',
      'bunca konu nasıl bitecek',
      'plan çok yoğun',
      'planımı hafifletir misin',
      'planı biraz azalt',
      'görevleri azaltalım',
      'bugünkü yük çok fazla azaltır mısın',
    ],
    // ------------------------------------------------------------------
    CoachIntent.lowProgress: [
      'bugün çalışamadım',
      'bugün hiç çalışamadım',
      'bugün hiçbir şey yapamadım',
      'bugün hiç çalışmadım',
      'bugün verimsiz geçti',
      'dün hiç çalışmadım',
      'iki gündür çalışamıyorum',
      'haftadır hiç çalışmadım',
      'bu hafta hiç çalışamadım',
      'bugün bir şey yapamadım',
      'bugün boşa geçti',
      'çalışmaya oturamadım',
      'masaya oturamadım bugün',
      'çalışayım dedim olmadı',
      'bir şey yapmadım bugün',
      'gün boyu boş durdum',
      'bugün tembellik ettim',
      'bugün çok az çalıştım',
      'bugün hedefimi yapamadım',
      'bugün planı yapamadım',
      'bugün görevlerimi yapmadım',
      'çalışamıyorum',
      'bir türlü çalışamıyorum',
      'çalışmaya başlayamıyorum',
      'verim alamıyorum',
      'verimli çalışamıyorum',
      'çalışıyorum ama hiçbir şey öğrenemiyorum',
      'saatlerce oturuyorum ama verim yok',
      'odaklanamıyorum',
      'konsantre olamıyorum',
      'dikkatim dağılıyor çalışamıyorum',
      'telefondan kopamıyorum çalışamadım',
      'günü boşa harcadım',
      'bugün hiçbir ilerleme yok',
      'bugün hiç ilerleyemedim',
    ],
    // ------------------------------------------------------------------
    CoachIntent.lowMotivation: [
      'motivasyonum yok',
      'motivasyonum çok düşük',
      'hiç motivasyonum kalmadı',
      'çalışasım gelmiyor',
      'çalışmak istemiyorum',
      'hiç çalışmak istemiyorum',
      'canım hiç çalışmak istemiyor',
      'içimden gelmiyor',
      'içim gelmiyor çalışmaya',
      'hevesim kalmadı',
      'isteksizim',
      'çok isteksizim bugün',
      'bıktım artık',
      'bıktım usandım',
      'çalışmaktan sıkıldım',
      'ders çalışmaktan bıktım',
      'sıkılıyorum çalışırken',
      'moralim bozuk',
      'moralim çok kötü',
      'çok yorgunum',
      'yorgunum çalışamam',
      'bitkinim hiçbir şey yapasım yok',
      'tükendim artık',
      'tükenmişlik yaşıyorum',
      'pes ediyorum',
      'pes edeceğim galiba',
      'bırakasım var',
      'her şeyi bırakmak istiyorum',
      'enerjim yok',
      'gücüm kalmadı',
      'kendimi çalışmaya zorlayamıyorum',
      'çalışmaya bir türlü motive olamıyorum',
      'motive olamıyorum',
      'sürekli erteliyorum çalışmayı',
      'hiçbir şey yapasım yok',
      'çalışmayı sevmiyorum artık',
      'uyuyasım var çalışasım yok',
      'nasıl motive olurum',
      'motivasyon lazım',
      'bir dürt beni motive et',
    ],
    // ------------------------------------------------------------------
    CoachIntent.progressConcern: [
      'ilerleyemiyorum',
      'bir türlü ilerleyemiyorum',
      'ilerleme kaydedemiyorum',
      'hiç ilerlemiyorum',
      'yerimde sayıyorum',
      'hiç gelişmiyorum',
      'gelişme göremiyorum',
      'emeğimin karşılığını alamıyorum',
      'çok çalışıyorum ama sonuç yok',
      'çalışıyorum ama netlerim artmıyor',
      'ne kadar çalışsam da olmuyor',
      'çalışmam boşa gidiyor gibi',
      'hedefime yaklaşamıyorum',
      'hedefe ulaşabilecek miyim',
      'hedefime yetişebilir miyim',
      'ilerlemem nasıl',
      'nasıl gidiyorum',
      'ne durumdayım',
      'iyi gidiyor muyum',
      'yeterince çalışıyor muyum',
      'yeterli mi bu tempo',
      'bu tempoyla olur mu',
      'sence yeterli çalışıyor muyum',
      'geçen haftaya göre nasılım',
      'gelişiyor muyum',
      'bir gelişme var mı',
      'durumum ne',
      'neredeyim şu an',
      'performansım nasıl',
      'kendimi geliştiremiyorum',
      'aynı yerde duruyorum',
      'hiçbir yere gitmiyor gibiyim',
      'ilerlediğimi hissetmiyorum',
      'çabam karşılık bulmuyor',
      'sürekli aynı seviyedeyim',
    ],
    // ------------------------------------------------------------------
    CoachIntent.generalProblem: [
      'bir sorunum var',
      'sorunum var yardım eder misin',
      'bir problemim var',
      'yardım eder misin',
      'yardıma ihtiyacım var',
      'kötü gidiyor',
      'her şey kötü gidiyor',
      'işler yolunda gitmiyor',
      'işler kötü',
      'durum kötü',
      'çok kötü durumdayım',
      'iyi değilim',
      'hiç iyi değilim',
      'olmuyor',
      'hiçbir şey olmuyor',
      'bir şeyler ters gidiyor',
      'berbat',
      'berbat bir durum',
      'rezalet',
      'çok kötü',
      'çaresizim',
      'çıkmazdayım',
      'kafam karışık',
      'kafam çok karışık',
      'karmaşa içindeyim',
      'derdim var',
      'dertliyim',
      'bir sıkıntım var',
      'sıkıntılıyım',
      'sana bir şey soracağım sorunum var',
      'çalışma konusunda sorunum var',
      'çalışmayla ilgili bir sıkıntı var',
      'ders çalışma konusunda sıkıntım var',
    ],
    // ------------------------------------------------------------------
    CoachIntent.positiveProgress: [
      'bugün çok iyi çalıştım',
      'bugün çok verimliydi',
      'bugün hedefimi tamamladım',
      'bugünkü planı bitirdim',
      'görevlerimi tamamladım',
      'tüm görevleri yaptım',
      'bugün güzel bir gündü',
      'iyi gidiyorum',
      'iyi gidiyor',
      'her şey yolunda',
      'çok iyiyim',
      'harika gidiyor',
      'süper gidiyor',
      'netlerim arttı',
      'deneme netim yükseldi',
      'denemede iyi yaptım',
      'son denemem çok iyiydi',
      'bu hafta çok çalıştım',
      'bu hafta hedefimi aştım',
      'matematik netim arttı',
      'matematikte ilerledim',
      'artık matematiği daha iyi anlıyorum',
      'konuyu anladım',
      'sonunda konuyu çözdüm',
      'başardım',
      'bir konuyu bitirdim',
      'seri yaptım bugün',
      'motivasyonum yerinde',
      'çok motiveyim',
      'kendimi iyi hissediyorum',
      'çalışmam iyi geçti',
      'bugün tam gaz çalıştım',
    ],
    // ------------------------------------------------------------------
    CoachIntent.thanks: [
      'teşekkürler',
      'teşekkür ederim',
      'sağ ol',
      'sağol',
      'çok sağ ol',
      'eyvallah',
      'saol',
      'tşk',
      'tşkler',
      'çok teşekkürler',
      'çok işime yaradı sağ ol',
      'harikasın teşekkürler',
      'yardımın için teşekkür ederim',
      'elinize sağlık',
      'sağ olasın',
      'mersi',
      'thanks',
      'teşekkürler koç',
      'tamam teşekkürler',
      'süper teşekkürler',
    ],
    // ------------------------------------------------------------------
    CoachIntent.confirmation: [
      'evet',
      'tamam',
      'olur',
      'tmm',
      'tabii',
      'tabi',
      'aynen',
      'ok',
      'peki',
      'anladım',
      'anlaşıldı',
      'kabul',
      'olsun',
      'evet lütfen',
      'evet olur',
      'tamam olur',
      'peki tamam',
      'tamamdır',
      'onaylıyorum',
      'uygun',
    ],
  };

  static int get totalCount =>
      byIntent.values.fold(0, (sum, list) => sum + list.length);
}
